### ISSUE TITLE
Fix some BS4 classes, quickview and carousel (Product slider)

### ISSUE THREAD

**Issue by rodriciru** [PrestaShop/theme-refacto#115]
Hi. I clone this repo and tested in ps 1.7.8.0.
I love. So much clean and modern. But i seen some BS4 classes, which dont work, and quickview and product slider its not woking.
I think i fix most of things i see, so i want to contribute. But i never do such a thing so im lost!. 
How can i help? 
Maybe with a Pull request?
This is my fork : https://github.com/rodriciru/theme-refacto

**Comment by SharakPL** [comment]
It's a theme for PS 8. Not compatible with PS 1.7.x

**Comment by rodriciru** [comment]
Ok. 
Anyway it work for 1.7.8 and the bs classes are wrong even in PS8 (in bs5 for example float-xs-left doesnt exist)

One qustion. I dont find any prestashop 8 version even in git develop branch. When i clone and install it say me 1.7.8.1, so where i can find the new version

**Comment by SharakPL** [comment]
Check the [description](https://github.com/PrestaShop/theme-refacto#readme):

> Please, if you work on this theme, use the develop branch of PrestaShop, because this theme will be available on 8.0

**Comment by rodriciru** [comment]
If I'm using 1.7.8.0 , I'm using PS8
That's correct? If yes  I'm doing well.

Ok. That's my contribution to the project I change some classes, so other don't need to do if the like my changes

**Comment by SharakPL** [comment]
> If I'm using 1.7.8.0 , I'm using PS8

No. You're using 1.7.8.0. PS8 is planned to be released early 2022. Current state of PS8 is in develop branch, on GitHub only. If you want to contribute, then check [THIS](https://github.com/PrestaShop/PrestaShop/blob/develop/CONTRIBUTING.md).

**Comment by alfonsolr09** [comment]
> If I'm using 1.7.8.0 , I'm using PS8
> That's correct? If yes  I'm doing well.
> 
> Ok. That's my contribution to the project I change some classes, so other don't need to do if the like my changes

the current version of PrestaShop is 1.7.8.x
After version 1.7.8.9 there would be version 1.8.0.0, but following the new version naming standards they will change the name to 8.0 (eliminating the 1 in front)

**Comment by rodriciru** [comment]
ok. I clone prestashop git, and the problem persis, as supposed.
So still thinking my fork has some useful code for the comunity

**Comment by NeOMakinG** [comment]
> Ok. Sorry about version mistake. I clone prestashop git, develop branch, and the problem persist, as supposed, because my fixes have nothing to do with PS version, just css classes So still thinking my fork has some useful code for the comunity

Hey @rodriciru, thanks for the support and love the fact that you appreciate the work we're currently on with the new theme!

There are a lot of things not finished yet, it's a `work in progress`, we didn't begin the quickview. Btw the product image slider should work at this time but it's maybe not finished.

Some classes can remains from the old theme, don't hesitate to provide a PR if you want to contribute to the project :)

**Comment by rodriciru** [comment]
Yes yes, i know its not close to finish this project.
I wil make a PR with QV some modal fixes, replace some BS4 classes by BS5 classes and slider in qv fixed.
Please check them and feel free to tell me anithing.
Thanks!
