### ISSUE TITLE
[FO] Too much product flags

### ISSUE THREAD

**Issue by SharakPL** [PrestaShop/theme-refacto#134]
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

Another issue following PrestaShop/PrestaShop#26640 . "Out of stock" label and basically all flags are loaded on product image covering essential information and even interfering with wishlist button:

![obraz](https://user-images.githubusercontent.com/5007456/145397109-d1993070-7b84-4bf6-a4ec-1c236426bd5f.png)
![obraz](https://user-images.githubusercontent.com/5007456/145397795-c7c42ad7-8f6f-4459-94c3-0f4be9d2264d.png)

And here's when product happens to have ~~all~~ some of them 😫

![obraz](https://user-images.githubusercontent.com/5007456/145404883-065e5d82-0f8b-4004-9f08-7997ccae0057.png)

### Expected behavior

Too much labels is thrown onto product image + labels are too big. Labels like that should be loaded below product price and even below [optional **Add to cart** button](https://github.com/PrestaShop/PrestaShop/issues/23496), just like it was in default theme of Prestashop 1.6. Anyway labels should have separate section not covering image.

### Steps to reproduce

1. Set product's amount to 0 on all combinations in BO to enable _out of stock_ label.
2. Open category containing this product on FO.

### PrestaShop version(s) where the bug happened

1.7.8.x

**Comment by NeOMakinG** [comment]
@SharakPL did ou test with new products flags inside theme-refacto? It's not way smaller

**Comment by MatShir** [comment]
It is a feature request that why I transferred it here :)
I think even if the labels are smaller we still have the same issue with too much flag into the product image if I got it right @SharakPL,

**Comment by SharakPL** [comment]
*Out of stock* doesn't really need a label. I mean it wouldn't if there was *Add to cart* button that would be in `disabled` state when product is out of stock. Anyway it's different kind of information than the discount amount, new or sale

Something [like this](https://dribbble.com/shots/14490351-Product-card/attachments/6175183) would be better:

![obraz](https://user-images.githubusercontent.com/5007456/145569421-405df2b0-7692-4ac0-8cc4-2e480f2d3fad.png)

or even like this where lables don't cover image at all:

![obraz](https://user-images.githubusercontent.com/5007456/145569747-ed146f8f-3b5a-46c9-a19d-849234e5f5ee.png)

And stock information should be right below Add to cart button

**Comment by NeOMakinG** [comment]
> _Out of stock_ doesn't really need a label. I mean it wouldn't if there was _Add to cart_ button that would be in `disabled` state when product is out of stock. Anyway it's different kind of information than the discount amount, new or sale
> 
> Something [like this](https://dribbble.com/shots/14490351-Product-card/attachments/6175183) would be better:
> 
> ![obraz](https://user-images.githubusercontent.com/5007456/145569421-405df2b0-7692-4ac0-8cc4-2e480f2d3fad.png)
> 
> or even like this where lables don't cover image at all:
> 
> ![obraz](https://user-images.githubusercontent.com/5007456/145569747-ed146f8f-3b5a-46c9-a19d-849234e5f5ee.png)
> 
> And stock information should be right below Add to cart button

I've a doubt but I think the out of stock label will be removed with the availability feature which is a WIP

**Comment by prestascott** [comment]
Hello @SharakPL,

Thank you for your suggestion. 

The stock label won't appear in the image but under the price. Like @NeOMakinG said, it's a WIP for the moment.
Also, the size of the label text will be smaller so that way it won't hide the product image.

Here is the design:
![image](https://user-images.githubusercontent.com/54888056/145594221-20e54a6c-43f0-44cd-92af-457d434e2ba7.png)

**Comment by SharakPL** [comment]
Love it! Thanks

**Comment by prestascott** [comment]
You're welcome. I guess we can close this issue now ^^

**Comment by SharakPL** [comment]
It's still an issue with classic, so how about move it back there? ;)

**Comment by alfonsolr09** [comment]
> It's still an issue with classic, so how about move it back there? ;)

I think exactly the same ...
