### ISSUE TITLE
Some Input elements can not be selected in product page

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/theme-refacto#143]
In some pages because of blockwishlist modal, some input elements placed at behind of blockwishlist form. So these elements can not be selected:

![Screenshot from 2021-12-20 14-24-21](https://user-images.githubusercontent.com/85633460/146757150-370108b1-3044-4e44-adc8-0fbb8fa23d67.png)

In product page click on wishlist button and close modal, then try to click initial part of the size dropdown or social links.

**Comment by mparvazi** [comment]
The content of blockwishlist is inside `<head>`:

![Screenshot from 2021-12-21 10-35-09](https://user-images.githubusercontent.com/85633460/146886498-c5c1716e-9871-487e-b448-a67acb86c352.png)

**Comment by SharakPL** [comment]
I think this should be reported on [blockwishlist's repo](https://github.com/PrestaShop/blockwishlist)

**Comment by matks** [comment]
@SharakPL Issues are not open on blockwishlist repo ;) we decided to keep all open bugs on main repo so they are in a single place

**Comment by mparvazi** [comment]
@SharakPL 

It's not related to blockwishlist, because with current classic-theme there is no problem.

It can be fixed in theme-refacto. For example:

```
product__col {
    position: relative
}

```
Then the `z-index` will be calculated correctly and blockwishlist form will be behind of page elements.

**Comment by mparvazi** [comment]
Wdyt about this code:

![Screenshot from 2021-12-21 12-42-58](https://user-images.githubusercontent.com/85633460/146903636-62a21251-98d2-4b2a-af50-43f810a7579b.png)

The content of blockwishlist is inside `<head>`:

![Screenshot from 2021-12-21 10-35-09](https://user-images.githubusercontent.com/85633460/146886498-c5c1716e-9871-487e-b448-a67acb86c352.png)

**Comment by SharakPL** [comment]
But it is the same problem on other themes, so it should be fixed in the module, not the theme.
Another would be interference with theme colors setup, eg. buttons on wishlist popup, which is damaging to the theme:

![wishlistbuttons](https://user-images.githubusercontent.com/5007456/146904369-16a789b5-0191-4728-81ab-e2524f2f0d58.gif)

**Comment by SharakPL** [comment]
> Wdyt about this code:
> 
> ![Screenshot from 2021-12-21 12-42-58](https://user-images.githubusercontent.com/85633460/146903636-62a21251-98d2-4b2a-af50-43f810a7579b.png)
> 
> The content of blockwishlist is inside `<head>`:
> 
> ![Screenshot from 2021-12-21 10-35-09](https://user-images.githubusercontent.com/85633460/146886498-c5c1716e-9871-487e-b448-a67acb86c352.png)
> 
> Is there any hook at bottom of body to add blockwishlist content?

This file is already hooked into footer, so it's not a problem here:

https://github.com/PrestaShop/blockwishlist/blob/1f9322fde7a114c185ff31ff1202c490351e16c9/blockwishlist.php#L260-L272

Look like it's Vue that attaches some modal parts into `<head>`

**Comment by mparvazi** [comment]
@SharakPL 

Fixed here:
https://github.com/PrestaShop/blockwishlist/pull/132

**Comment by SharakPL** [comment]
Yeah, I know. I'm just saying displayHeader.tpl that you mentioned isn't the one generating divs inside `<head>`.

**Comment by mparvazi** [comment]
> Yeah, I know. I'm just saying displayHeader.tpl that you mentioned isn't the one generating divs inside `<head>`.

![Screenshot from 2021-12-21 13-24-41](https://user-images.githubusercontent.com/85633460/146909804-65cc5212-05cb-41ea-baaa-538a7a270684.png)

Btw it fixed!

**Comment by SharakPL** [comment]
So it seems the main issue here is that new version of blockwishlist hasn't been relaesed since May 😉
Issue with button colors is also fixed https://github.com/PrestaShop/blockwishlist/commit/2ff8b57042cb590ecbfaa8d0770243383e679f89
