### ISSUE TITLE
Slick JS in theme-refacto (I don't understand something)

### ISSUE THREAD

**Issue by fdonnet** [PrestaShop/theme-refacto#145]
Hi,

I m trying to play with the new cool theme and woudl like to integrate slick.js.

It seems that I have a conflict with the way the new theme import jQuery.
When I keep the slick js like it is  (top of the slick.js file below)
```JS
;(function(factory) {
    'use strict';
    if (typeof define === 'function' && define.amd) {
        define(['jquery'], factory);
    } else if (typeof exports !== 'undefined') {
        module.exports = factory(require('jquery'));
    } else {
        factory(jQuery);
    }

}(function($) {
```
I have this error msg 
`Uncaught Error: [exposes-loader] The "$.jQuery" value exists in the global scope, it may not be safe to overwrite it, use the "override" option`

When I comment this part and think => jquery is already exposed 
```JS
;(function(factory) {
    // 'use strict';
    // if (typeof define === 'function' && define.amd) {
    //     define(['jquery'], factory);
    // } else if (typeof exports !== 'undefined') {
    //     module.exports = factory(require('jquery'));
    // } else {
    //     factory(jQuery);
    // }

}(function($) {
```
I was not able to access the function `.slick`
`Uncaught TypeError: self.slick is not a function`

I tried with TS, I tried to import slick.js different ways etc but I always fall on this exact same behavior

Maybe I don't understand how jQuery is declared in this new theme and what I need to do. It was working perfectly well with the old classic theme. 
I think I will have the exact same issue with other external lib I would like to integerate, so I request your wise advices ;)

**Comment by SharakPL** [comment]
jquery is loaded in /themes/core.js of prestashop installation ([src](https://github.com/PrestaShop/PrestaShop/blob/develop/themes/_core/js/theme.js)). That's why it's exposed globally:

https://github.com/PrestaShop/theme-refacto/blob/09d087a9999e199c053193cabbc095cf89148e81/webpack/webpack.parts.js#L152-L169

It will probably remain there since a lot of modules will still use jquery, but I assume theme itself won't be using it since it's built on Bootstrap 5 which uses just javascript. No jquery is needed for this. Additional plugins and modules should import it again, because it's already there in core.js

**Comment by fdonnet** [comment]
Yes I understand that but I don't know why this Slick compo doesn't understand that jquery is already there. It seems related to theme and I would like to know how to integrate it correctly... it is very strange

**Comment by SharakPL** [comment]
It may be exposed globally but you still need to import it, just like classic theme does. You'll probably also need to restore `jQuery` and `$` as `externals` in webpack config, along `prestashop` to avoid duplicating it in your theme assets. Just check how classic does it.

**Comment by fdonnet** [comment]
Ok, I will try but it seems this theme already use `$` for jquery in other module but maybe it is my mistake... i will continue to investiguate. Thx for the help.

**Comment by SharakPL** [comment]
Try simply uncommenting this line:

https://github.com/PrestaShop/theme-refacto/blob/develop/src/js/theme.ts#L27

**Comment by fdonnet** [comment]
Already tried before my post. Same first error 
`Uncaught Error: [exposes-loader] The "$.jQuery" value exists in the global scope, it may not be safe to overwrite it, use the "override" optio`

**Comment by fdonnet** [comment]
This specific line causes exactly the same issue as the first part in the slick.js lib...

**Comment by SharakPL** [comment]
Do you import slick's bundle or slick source?

**Comment by fdonnet** [comment]
I tried both, via npm and via source

**Comment by fdonnet** [comment]
Maybe I will go with another carousel. My goal is to have product carousel for new products or featured products (responsive and with the swipe for mobile etc)... slick was just perfect and ez for that on the classic theme.

**Comment by SharakPL** [comment]
You could simply use CDN or better yet switch to Swiper maybe, as Slick hasn't been improved since 2019.

**Comment by fdonnet** [comment]
k, I will try. Thx again for the help !

**Comment by SharakPL** [comment]
> Maybe I will go with another carousel. My goal is to have product carousel for new products or featured products (responsive and with the swipe for mobile etc)... slick was just perfect and ez for that on the classic theme. 

I get that. I've been also using Slick for a long time, but at some point I needed to make a 2-rows carousel so I had to switch to something more advanced. Turned out Swiper has all I need. Although it is quite heavy so you would probably customize it for your needs.

**Comment by fdonnet** [comment]
Yes I will look at it and try to do something clean with a good integration for this new TS/Bootstrap 5 theme... Slick was the "cool & quick way" but maybe I will find something better.

**Comment by fdonnet** [comment]
@SharakPL hey I solved my issue...
On top of the slick.js file I replaced like this 
```
+(function($) {
  'use strict';
  var Slick = window.Slick || {};
```
no more factory and define etc

and at the end 
`})(jQuery);`

I tried to do exactly like here https://github.com/avinoamr/bootstrap-carousel-swipe/blob/master/carousel-swipe.js
It seems to work to transfer Jquery to the lib...
I m happy.
+++

**Comment by NeOMakinG** [comment]
@fdonnet @SharakPL I didn't take the time to investigate on a light way of using Swiper yet but I really want to check if this is possible in order to provide the most complete lib for every slider

And sorry I was in vacations so I wasn't able to help you @fdonnet, but cool that you found a way to make it work :)

**Comment by fdonnet** [comment]
I stay on slick for the moment, but yes @NeOMakinG Swiper seems super cool
this kind of things : https://carousel-slider.uiinitiative.com/ are awesome (i can see products in there) ;) 
Hope you had good holidays. I will follow your theme-refacto initiative it is top, thx for that.
