### ISSUE TITLE
Adding sidebar quickview for Shopping Cart

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/theme-refacto#166]
https://user-images.githubusercontent.com/85633460/150799696-97bcb9ab-2cb2-4d09-8fdb-206ec80eb8f6.mp4

**Comment by mparvazi** [comment]
I meant adding a quick-view for shopping cart that user can see shopping cart in all pages.
As like as quick-view for product. 
It doesn't impact the shopping cart page.

**Comment by mparvazi** [comment]
https://user-images.githubusercontent.com/85633460/150812838-6d062cc5-6dc6-44bb-b933-b93b1941cc4d.mp4

**Comment by mparvazi** [comment]
https://user-images.githubusercontent.com/85633460/150816294-0f9e7f42-40af-4e54-9677-f8585032e32d.mp4

**Comment by Hlavtox** [comment]
Love it

**Comment by NeOMakinG** [comment]
In term of animation, I don't like the fact that the text width is reducing when you close the modal, and increasing when you open it

Btw, I'm really not against this feature, but I surely think that we shouldn't add it to the default theme

- The theme is really big already, with a lot of possibilities, it's pretty hard to maintain properly so, adding more and more features increase the maintaining pain
- Modules are designed to extend the theme possibilities, maybe this is the role of a module

wdyt?

**Comment by adamus007p** [comment]
I agree with @NeOMakinG that that feature should not be in default theme.

Customers are not used to that functions and from UX perspective it is not the best solution.
It could be a feature if someone want to get a fancy shop.

Please remember that we create shop for customers not for developers who know how to use PC.
Everything should be a stupid simple, every click or scroll may  be an effort.


Lets say someone is older, or do not see and use the second scroll and it may be confused what is going on.

The best way it watch customers using some tools to record shops and see what customers are doing, you will find a things which you would never do, but customers do :)


Customer flow, each steps who lead to order are very important.


Feature is nice but I my opinion it should not be in default shop.

**Comment by Hlavtox** [comment]
> Everything should be a stupid simple, every click or scroll may be an effort.

Couldnt agree more!

**Comment by mparvazi** [comment]
@NeOMakinG 

I used Bootstrap5 features for sidebar.
Just couple of lines of codes.

**Comment by Hlavtox** [comment]
@mparvazi @NeOMakinG Can we do something like "experiments" folder/css in the theme, so everybody with at least SOME knowledge can customize and build on it even with more ease? And use this feature for example?

The same could maybe go for "Show all products" button, we can just comment it out, but keep it in the template? WDYT?

**Comment by adamus007p** [comment]
I think that this is a feature but not something which should be mandatory or by default in new theme that I may cause UX problems.

Two scrolls one by one it is not the best.

Use tablet and see. Different thing is when you use tablet mode on PC and you have a mouse, different thing is when you test something on real devices. This is common mistake during project.


Where can I ask off topic question?
I wanted to ask about ETA of new theme and will it have a dark/light mode to change colors?

**Comment by mparvazi** [comment]
@Hlavtox 

IMO using CSS file for customization isn't maintainable and it's opposite of the goals of theme-refacto.
We can add a config page for each them in BO > themes, so user can control the current components or add new component.

Btw we should consider this:

> The theme is really big already, with a lot of possibilities, it's pretty hard to maintain properly so, adding more and more features increase the maintaining pain

**Comment by Hlavtox** [comment]
@adamus007p Hit us on slack - https://join.slack.com/t/prestashop/shared_invite/zt-dkmbz5qf-I~FlEWwmRUOXunc5ui0Ucg

**Comment by NeOMakinG** [comment]
> @Hlavtox
> 
> IMO using CSS file for customization isn't maintainable and it's opposite of the goals of theme-refacto. We can add a config page for theme in BO > themes, so user can control the current components or add new component.
> 
> Btw we should consider this:
> 
> > The theme is really big already, with a lot of possibilities, it's pretty hard to maintain properly so, adding more and more features increase the maintaining pain

Btw, this can be an open source module idea, where people could contributes on adding new components (But I think PrestaShop won't want to maintain it)

**Comment by mparvazi** [comment]
> Btw, this can be an open source module idea, where people could contributes on adding new components (But I think PrestaShop won't want to maintain it)

The config page in BO, or module for configuration must use CSS for config file (override rules).
For example `custom.css`

So maintaining a module that always must be synchronized with last changes of theme-refacto would be troublesome!
