### ISSUE TITLE
Optimizing UX for faceted search on mobile screen

### ISSUE THREAD

**Issue by mparvazi** [PrestaShop/theme-refacto#169]
When the media screen is mobile, we can hide Category tree and Faceted search filter.
A button will be added alongside of the category name for each of them.

<img src="https://user-images.githubusercontent.com/85633460/152313620-ad67471b-2d73-48c2-bc21-a30f4cad3743.png" width="300">

When user select a button, corresponding content will be displayed in full screen.
For faceted search the content will be remained until user select Apply button.

<img src="https://user-images.githubusercontent.com/85633460/152314526-e9bb86fe-cdb1-48b5-9ed2-4759e07711d8.png" width="300">

**Comment by NeOMakinG** [comment]
Hey @mparvazi 

https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=173%3A12443

Did you see the mockups?

For the number of product in the button, is it the current number of product displayed? I'm afraid users would think that this is the result number

**Comment by mparvazi** [comment]
Hello @NeOMakinG 

I didn't check mock-up for faceted search.
Your design idea is much better :100:  :+1:
