### ISSUE TITLE
Theme Options

### ISSUE THREAD

**Issue by DracoBluee** [PrestaShop/theme-refacto#175]
A handling module that introduces some changes to the template, changes in color, button layout, etc.

**Comment by NeOMakinG** [comment]
Currently, we don't want to add more works to this project with such a thing, if you want to create it and maintain it yourself, feel free, if we need to adapt the theme for some needs, we can too!

Feel free to reopen it if you think that my opinion is wrong @PrestaShop/prestashop-maintainers
