### ISSUE TITLE
[RESPONSIVE - Sign in Page] Create this new page

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/theme-refacto#18]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=289%3A14438)

**Comment by NeOMakinG** [comment]
Same as the responsive issue, impossible to do atm
