### ISSUE TITLE
[DESKTOP - My account Page] Personal information

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/theme-refacto#20]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2
Responsive's issue: https://github.com/PrestaShop/theme-refacto/issues/26

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=236%3A10538)

#### UX and design explanations
- The "Mx." social title has been added for gender-neutral, people who don't identify themself as male or female (of course, social titles can be managed by users in the back office)
- Mandatory inputs have a red asterisk

#### Mockup
![desktop - personal information](https://user-images.githubusercontent.com/54888056/137760569-c1be4deb-6860-4fad-b62a-08565eacf45c.png)

**Comment by NeOMakinG** [comment]
Closing it for the moment

Only thing left: multiple column layout, it's impossible with the backend we have at the moment
