### ISSUE TITLE
[DESKTOP - My account Page] Order history and details

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/theme-refacto#22]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2
Responsive's issue: https://github.com/PrestaShop/theme-refacto/issues/28

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=236%3A10538)

#### UX and design explanations
Alignement
- The header text is differentiated from column text by a heavier weight. It makes the header easy to read with its contrast.
- The numeric alignment is applied for data related to size (e.g. the currency). The font used for numeric alignment is "Monospace", also known as "Tabular" font. This means that a wide letter such as "W" that is bigger than "I" will have the same width. It allows users to scan numerical data easier.
- Textual data is aligned to the left (e.g. Order reference or Payment)
- Headers are aligned according to their column data

Order details
- Sections are better defined and identifiable by dividers and section titles (e.g. Addresses, Products, Tracking, etc)
- In terms of alignment, the same rules apply
- Image of the purchased product has been added so customers can remember the look of the product
- Total price is differentiated from the rest by a heavier weight to create a contrast so it can easily be identified
- Affordance has been improved by transforming the "Reorder" link into a button

#### Mockups
Order history and details
![desktop - order history and details](https://user-images.githubusercontent.com/54888056/138106376-cc6fefc8-2eb4-4826-8da9-0c1f3c28e30e.png)

Order details
![desktop - order details](https://user-images.githubusercontent.com/54888056/138243179-0082f241-1967-4baa-9c72-8ffbd8bd70e6.png)

**Comment by prestascott** [comment]
@PrestaEdit Did you click on this link? Because it's inside [here](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=254%3A10593) :) 

The prototype isn't ready anyway, that's why I didn't write the UX and design explanations yet

**Comment by PrestaEdit** [comment]
I click on the link mention inside this issue, and it's not this one ;-)

**Comment by PrestaEdit** [comment]
Thansk @prestascott ; strange that yesterday I don't see it. Don't know if it could be a cache or not but, yeah, it's there ;-)
