### ISSUE TITLE
[DESKTOP - Component] Menu

### ISSUE THREAD

**Issue by NeOMakinG** [PrestaShop/theme-refacto#53]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=47%3A286)

#### UX explanation

**Comment by NeOMakinG** [comment]
Same as the responsive issue

**Comment by Kreamxxx** [comment]
its possible to change the menu module ?
