### ISSUE TITLE
[DESKTOP - Manufacturer Page] Manufacturer listing

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/theme-refacto#70]
@prestascott Pls create a sketch. :-)

My implementation: https://www.trendo.cz/znacky

**Comment by prestascott** [comment]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2
Responsive's issue: 

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=1277%3A18453)

#### UX and design explanations
- Simply the brand image and the name of the brand below

#### Mockup
![desktop - manufacturer page](https://user-images.githubusercontent.com/54888056/137503946-304fedf9-258c-420d-8b77-93afc9b7ae2b.png)
