### ISSUE TITLE
[RESPONSIVE - Store Page] Page 

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/theme-refacto#86]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2
Desktop's issue: https://github.com/PrestaShop/theme-refacto/issues/85

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=1257%3A20445)

#### UX and design explanations
- Unfortunately, there wasn't enough space to keep 2 store cards in the same row
- I added an icon before the country in the address to make it more identifiable
- Days are aligned on the left to make it easier to read since the space between the day and the schedules was tiny

#### Mockup
![responsive - store page](https://user-images.githubusercontent.com/54888056/137506293-9116022e-712f-4701-a993-e4a4b2419ee0.png)

**Comment by alfonsolr09** [comment]
think that maybe it would be a good idea to put a drop-down arrow to each store, since if you have several stores it will be a very long page.
I propose to create it in the form of a drop-down to open the one that really interests you

**Comment by prestascott** [comment]
@alfonsolr09 Maybe we can only hide the schedules because the information above is relevant for users.

**Comment by alfonsolr09** [comment]
Good idea

**Comment by NeOMakinG** [comment]
Opening it again so we don't lose this feedback!

**Comment by NeOMakinG** [comment]
Done, it has an accordion with `See schedules`

**Comment by prestascott** [comment]
@NeOMakinG Can you send some screenshots please?

**Comment by NeOMakinG** [comment]
![image](https://user-images.githubusercontent.com/14963751/146207086-9c84a762-6ba9-405b-9b62-58a67958ec97.png)
![image](https://user-images.githubusercontent.com/14963751/146207108-6f141669-ca1c-46a5-874b-fe6e1c302a10.png)

**Comment by prestascott** [comment]
Great @NeOMakinG! 

Can you replace "See schedules" by "View schedules"? Thank you 🙏

**Comment by alfonsolr09** [comment]
amazing improvement 😊👌👌

**Comment by alfonsolr09** [comment]
Don't you think that to the right of the image there is a lot of empty space? @NeOMakinG

**Comment by NeOMakinG** [comment]
> Don't you think that to the right of the image there is a lot of empty space? @NeOMakinG

Depend of the length of the address I think so, but yes, just following @prestascott mockups, see with him :)

**Comment by SharakPL** [comment]
The point of image there is to see the presentation of the shop. IMO image should fill the width of the card.

**Comment by alfonsolr09** [comment]
> IMO image should fill the width of the card.

im agree @prestascott

**Comment by alfonsolr09** [comment]
> just following @prestascott mockups, see with him :)

look firts mockups... 
![image](https://user-images.githubusercontent.com/62474824/146660471-b17ddacb-9ca4-4461-9160-22cd7b132f13.png)

**Comment by prestascott** [comment]
Hey @alfonsolr09,

It might seems that there is a lot of empty space but it really depends on the content. On this example, the address in the United States is quite short.

The card length depends on the grid columns and not the content inside.

**Comment by alfonsolr09** [comment]
maybe it should be adapted to the content of the interior?
what if the text is very long? will there always be such a large margin on the right side?

**Comment by prestascott** [comment]
@alfonsolr09 of course not, they won't.

**Comment by NeOMakinG** [comment]
Well it looks like my screens comes from a small screen where stores are at 100% anyway

**Comment by alfonsolr09** [comment]
another idea, in the classic theme there is no this function and I think it could be a very good idea
add `<a href="tel:+00 000 000 000">`
add `<a href="mailto:mail@mail.com">`

instead of just displaying that information

**Comment by alfonsolr09** [comment]
I refer in this same section, in About and Contact
