### ISSUE TITLE
[RESPONSIVE - Contact us Page] Page

### ISSUE THREAD

**Issue by prestascott** [PrestaShop/theme-refacto#92]
Epic: https://github.com/PrestaShop/theme-refacto/issues/2
Desktop's issue: https://github.com/PrestaShop/theme-refacto/issues/91

[Link to Figma prototype](https://www.figma.com/file/LfVl5leeSKcVUhSaYwhbtM/New-Theme?node-id=1257%3A20444)

#### UX and design explanations
- The form has been improved by adding an asterisk when input is mandatory

#### Mockup
![responsive - contact us](https://user-images.githubusercontent.com/54888056/137509145-b9d706db-b2e3-46f0-8b83-139059232294.png)

**Comment by alfonsolr09** [comment]
I think the store information should be below the contact form @NeOMakinG

**Comment by alfonsolr09** [comment]
like this https://www.awesomescreenshot.com/image/18712110?key=fcae1c20935d0d4536cc2784830e2711
