### ISSUE TITLE
How to call a new theme?

### ISSUE THREAD

**Issue by Hlavtox** [PrestaShop/theme-refacto#96]
The theme needs a name. What about:

- TwentyTwo
- Eight

Ping @NeOMakinG

**Comment by SharakPL** [comment]
How about Alpha, to honor Bootstrap alpha used so many years 😉

**Comment by Hlavtox** [comment]
@SharakPL 🤣🤣🤣

**Comment by davidglezz** [comment]
`modern`

**Comment by alexandrebrubeyonds** [comment]
Slate 🙄

**Comment by Oksydan** [comment]
> # modern

@davidglezz it is already taken 😂

**Comment by tswfi** [comment]
Theme McThemeface

(I'll show my self out)

**Comment by Seb33300** [comment]
We should call it Seb33300

**Comment by jf-viguier** [comment]
neoclassic theme, a reference to NeOMakinG pseudo because he's worth it

**Comment by Kaudaj** [comment]
`twenty-two` will be too similar to WordPress imo.
Why should we take a different one than the new back-office theme (`modern`)?
Otherwise, I join @jf-viguier for `neoclassic` !

**Comment by SharakPL** [comment]
`Default`, `Theme8` (I suspect there will be new theme for each new major version so I suggest including it in the name), `Alpha` (I'm serious! 😛 )

**Comment by Kaudaj** [comment]
Yea, we should pick something generic to really emphasize that it's the default theme imo.
Will it really be a new theme for each major version?

**Comment by SharakPL** [comment]
> Will it really be a new theme for each major version?

It's been like that so far.

**Comment by Oksydan** [comment]
> Yea, we should pick something generic to really emphasize that it's the default theme imo. Will it really be a new theme for each major version?

No way. It isn't possible but we still don't know when new theme will be available. It might be v8, v8.1 or even v9 🤷🏼‍♂️. It all depends on your contribution to this project.

**Comment by NeOMakinG** [comment]
> > Will it really be a new theme for each major version?
> 
> It's been like that so far.

I think it won't be the case since the major release rhythm should also change, we won't be able to develop a new theme every year approx.

We will probably maintain the new theme, instead of developing another one it would be too hard for everyone to follow honestly

**Comment by NeOMakinG** [comment]
> > Yea, we should pick something generic to really emphasize that it's the default theme imo. Will it really be a new theme for each major version?
> 
> No way. It isn't possible but we still don't know when new theme will be available. It might be v8, v8.1 or even v9 🤷🏼‍♂️. It all depends on your contribution to this project.

Doing my best, @Hlavtox is helping a lot too, you did a great job on dev tools, I really hope we will have it on v8 🙏

**Comment by SebSept** [comment]
`Temptation` ? 
`Themptation` ?
`Rethemption` ?

**Comment by Hlavtox** [comment]
@NeOMakinG `default-boostrap` to honor the good times

**Comment by Kaudaj** [comment]
Won't referring to Bootstrap in the name confuse end users?

**Comment by NeOMakinG** [comment]
> Won't referring to Bootstrap in the name confuse end users?

We won't choose this I think so 😆

**Comment by Hlavtox** [comment]
I wonder how this will be approached and chosen, mainly after the last OSS demo ensuring the “opensourceness” of the project. 😛

**Comment by alexandrebrubeyonds** [comment]
Agree with @jf-viguier 
**neoclassic**

**Comment by alfonsolr09** [comment]
But I think that the theme should be built first and finally look for a name, do you agree?

**Comment by NeOMakinG** [comment]
> But I think that the theme should be built first and finally look for a name, do you agree?

Both is possible, we already know how the theme would look, it's going pretty fine atm, why not creating a discussion at the same time :)

**Comment by PululuK** [comment]
**sexytheme**

**Comment by PietaH** [comment]
Homebase?

**Comment by Hlavtox** [comment]
@PululuK **toosexy** 😄

**Comment by eveneme** [comment]
ProSilver

**Comment by templatin** [comment]
I think we also need to assure that it doesn't conflict with third-party theme names.
So my suggestion would be `default-classic`

**Comment by jf-viguier** [comment]
@NeOMakinG any update on the naming ?

**Comment by NeOMakinG** [comment]
> @NeOMakinG any update on the naming ?

Unfortunately not atm, didn't took the time to go further, we need to select some names and set a poll on the OS slack so everyone vote!

**Comment by PierreRambaud** [comment]
`neoclassic` ftw

**Comment by davidglezz** [comment]
`default-basic`

**Comment by NeOMakinG** [comment]
Only a few days are left in order to provide some ideas, afterwhile we will make a choice, thanks everyone for your suggestions :)

**Comment by jatniel** [comment]
`classic-boostrap`

`classic-eight`

**Comment by mparvazi** [comment]
`default`

`modern`

The third-party theme names should be considered.

**Comment by lucrp** [comment]
`infinity` in reference to the 8 and infinity math symbol

**Comment by dennispw** [comment]
Supposing that "classic" is the most recognisable name from PrestaShop then I would also go with `classic-eight`. Next major version would then be `classic-nine` and so on.

I would refrain from adding anything framework related to the name. Even more so if the new theme is made in a way where implementing any desired framework is easy/encouraged/documented/etc. It could also be a deterrant for those who perhaps don't want to work with Bootstrap (in this case).

**Comment by mparvazi** [comment]
@dennispw 

`classic` kinda refer to old!

Wdyt?

**Comment by dennispw** [comment]
> @dennispw
> 
> `classic` kinda refers to old!
> 
> Wdyt?

I guess that depends on how you look at, or frame, it. Personally I don't put much weight on the actual word "classic" and the meaning of it but rather that "classic" in this case is closely related to PrestaShop. It could be called "lollypop" for all I care if that in itself was tied to PrestaShop as closely as "classic" is at this time.

**Comment by SharakPL** [comment]
`classic` is tied to many things, so I don't see any strong relation. If you look for something tied with Prestashop, then maybe `preston` or `preston-eight`.

**Comment by davidglezz** [comment]
`ps_theme`
`base-theme`
`modern-minimal`
`modern-basic`
`armpit`

**Comment by kpodemski** [comment]
As much as I like the `neoclassic` I would go for `classic-eight`, or `classic-nine` depending on the major version when we will see it.

**Comment by dennispw** [comment]
> `classic` is tied to many things, so I don't see any strong relation. If you look for something tied with Prestashop, then maybe `preston` or `preston-eight` or `preston-classic`.

I was going to give Preston based suggestions as well but I recall someone saying the mascot would be retiring soon (or already retired?). I can't remember where, might have been on Slack, so definately *do not* take my word for it! I might very well be confusing it with something else.

**Comment by NeOMakinG** [comment]
> As much as I like the `neoclassic` I would go for `classic-eight`, or `classic-nine` depending on the major version when we will see it.

But do we really want to create a new theme on every major version? I'll ask the team about this

**Comment by SharakPL** [comment]
Won't there be new theme for each new major release? So far that's how it's been.

**Comment by Kaudaj** [comment]
@SharakPL https://github.com/PrestaShop/theme-refacto/issues/96#issuecomment-957965059

**Comment by matks** [comment]
> Won't there be new theme for each new major release? So far that's how it's been.

I think we build a new theme when it's needed. As PS 1.7 has stayed for a very long time, a rework was definitely needed because Classic was very old and has major weaknesses.

If PrestaShop 9 is released 2 years after PrestaShop 8 maybe there will not be such a big need.

**Comment by SharakPL** [comment]
Ok. Although 1.7.0 was released over 5 years ago, I doubt a lifespan will be this long for next versions. So it really isn't a good idea to include version number. Especially that this new theme is going to be used in many future releases. Maybe `prestheme`.

**Comment by NeOMakinG** [comment]
Yeah this is why I had a doubt about versioned names, but it will be versioned by composer I think so, even if there is a major release more frequently, we can maintain it with some BC breaks on every majors (and of course deprecation between versions)

**Comment by NeOMakinG** [comment]
Anyway, we will make a selection between multiple names and create a poll so everyone will be able to vote for it, then this issue will be definitely closed

You've around 5 days left before we create the poll :)

**Comment by eternoendless** [comment]
I like neoclassic, but I also like the idea of having something generic that we can keep for the long run.

Some ideas for generic names could be:
* default
* defaulttheme
* ecommerce
* prestashop
* frontoffice
* frontside
* storefront (I kind of like this one, but that's what woocomerce uses)

Keep in mind that theme names can only have letters and numbers (no dashes or other symbols are allowed AFAIK)

**Comment by Kaudaj** [comment]
@eternoendless It has changed then, because I used to add dots and underscores in my themes... 🤔

**Comment by alfonsolr09** [comment]
Wdyt about 'classic pro' ??

**Comment by tswfi** [comment]
classic22

And fast forward few years when this discussion is raised again: classic24 etc

**Comment by Hlavtox** [comment]
If you go for **Eight**.
- Its short.
- Its nice.
- It marks a point in history where PS went really open source, got usable and crap was removed.
- When you make a new theme, you follow the same logic and call it Thirteen or something.

**Comment by jf-viguier** [comment]
@Hlavtox I like your proposal "Eight", but it's maybe too close to wordpress logic.

**Comment by eternoendless** [comment]
> It has changed then, because I used to add dots, hyphens and underscores in my themes... 🤔

@Kaudaj I don't think it will work with translation domains

@Hlavtox I also thought about Eight and I quite like it, but I think it will be weird if we keep it (as we most likely will) as default for v9 as well

**Comment by Kaudaj** [comment]
Ah yea, it's themes I'm currently building and didn't add translations atm. So good to know!

**Comment by NeOMakinG** [comment]
We decided to select a list of names, it's now the time to vote!

https://framaforms.org/vote-for-the-new-theme-name-1644576025

You've until 02/18/2022 to vote!

Thanks everyone :)

**Comment by jf-viguier** [comment]
Voted

**Comment by alexandrebrubeyonds** [comment]
Done

**Comment by adamus007p** [comment]
I am late, but my idea was classic8. The number would show the compatibility with Prestashop v.8, later it could be changed to classic8.

Classic8 or default8

**Comment by eternoendless** [comment]
@adamus007p classic is compatible with v8

**Comment by adamus007p** [comment]
@eternoendless thank you for info.

Voted

**Comment by matks** [comment]
Announced during the Public OSS Demo of March, the new theme will be called hummingbird theme :)

https://build.prestashop.com/news/public-demo-2-2022/
